"""add transaction_date

Revision ID: 583b9bb28c43
Revises: 009
Create Date: 2026-05-02 05:24:09.286025+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583b9bb28c43'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('transaction_date', sa.Date(), nullable=True))
    op.add_column('incomes', sa.Column('transaction_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'transaction_date')
    op.drop_column('expenses', 'transaction_date')
    # ### end Alembic commands ###
