"""make email nullable

Revision ID: 93b2653e2316
Revises: 010
Create Date: 2026-05-02 11:37:31.512623+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b2653e2316'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ai_analysis_period_user_active', table_name='ai_analyses', postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint('uq_ai_analysis_period_user', 'ai_analyses', ['period_key', 'user_id'])
    op.drop_index('ix_transactions_transaction_date', table_name='transactions')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('ix_transactions_transaction_date', 'transactions', ['transaction_date'], unique=False)
    op.drop_constraint('uq_ai_analysis_period_user', 'ai_analyses', type_='unique')
    op.create_index('uq_ai_analysis_period_user_active', 'ai_analyses', ['period_key', 'user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
